### ISSUE TITLE
Official way to synchronize the JSON 5.0 feeds

### ISSUE THREAD

**Issue by ncrocfer** [CVEProject/cvelistV5#16]
Hello,

First of all thank you for the awesome work you do concerning the CVE ecosystem!

I'm the developer of a CVE-related tool, and I would like to add the MITRE in my sources (instead of only relying on NVD for now). But to be honest I don't really know how to parse your feed.

So I would like to ask you the official and recommended way to synchronize our local databases with the new JSON 5.0 CVE list.

I searched on your blog posts and if I'm not wrong you're currently in "Soft Deploy" state, meaning CNAs now use the new format to declare CVEs. The "Hard Deploy" is targeted for 1st QT, 2023. At this moment we (as consumers) will be able to officially use the JSON 5.0 feeds.

But where to find the list please? I think the old format (`cvs`, `html`, `text`, `xml`) will be removed, so maybe you will provide an API (or something similar as the [NVD does](https://nvd.nist.gov/developers/api-workflows)) to fetch the last changes?

Or maybe this current repo (cveproject/cvelistv5) will become our official data feeds?  If yes do you recommend to use the `recent_activities.json` file to detect the changes or simply periodically `git pull` and parse the new diffs?

Thank you in advance for your answer,
Nicolas

**Comment by hkong-mitre** [comment]
As of 3/28/2023, this repository is now the official way to download/update all published CVEs from the official CVE Project.  You can think of it as a cache that is updated multiple times an hour.

There are now 3 methods to download/sync the CVEs:
1. if you are comfortable with using `git`, use any git client and `git clone https://github.com/CVEProject/cvelistV5.git` as you would any GitHub repository.  The initial `git clone` is quite large (about 1.7 GB), but each successive `git pull` will quickly update your local clone.  This is the preferred approach and can be easily automated.
2. if you prefer to use zip, use this repository's [Releases Page](https://github.com/CVEProject/cvelistV5/releases) where you can choose download a "baseline" zip containing all CVEs at midnight (GMT), an hourly zip containing all new/updated CVEs since midnight (GMT), and/or a release note enumerating all the new/updated CVEs since midnight (GMT).  This approach uses about 1.5 GB of storage.  Use this method if you need a daily sync (e.g., at or close to midnight GMT every night) or hourly syncs throughout the day.
3. if you want to download all current CVEs infrequently, use GitHub's "Download Zip" link.  This downloads all of the current CVEs in a single large zip file.  This method is not recommended for sync purposes, since it always downloads *all* CVEs each time

**Comment by M-nj** [comment]
@bytedancer1 I believe the delta files might be of interest for you? 

For changes that happened in the **latest commit** see [cves/delta.json](https://github.com/CVEProject/cvelistV5/blob/main/cves/delta.json).

For changes that happened in the **latest few commits** see [cves/deltaLog.json](https://github.com/CVEProject/cvelistV5/blob/main/cves/deltaLog.json). 
_Note: The deltaLog.json does not guarantee a set time window (e.g. last X days) or number of commits (e.g. last X commits). The git log rotates out X days ago, but it is possible for it to drop a few of the older commits if there are too many in the file. [The source code can be found in the cvelist-bulk-download repo here (TS/JS)](https://github.com/CVEProject/cvelist-bulk-download), specifically the [`Automated github action to run the update/commit command`](https://github.com/CVEProject/cvelist-bulk-download/blob/main/github-actions/update.yml), [`UpdateCommand`](https://github.com/CVEProject/cvelist-bulk-download/blob/main/src/commands/UpdateCommand.ts), [`Delta`](https://github.com/CVEProject/cvelist-bulk-download/blob/main/src/core/Delta.ts), and [`DeltaLog`](https://github.com/CVEProject/cvelist-bulk-download/blob/main/src/core/DeltaLog.ts) files._


#### Quick rundown for the delta file contents:
```js
{
  // fetchTime: the UTC+0/Z timestamp for when this update command started
  "fetchTime": "1970-01-01T00:00:00.000Z", 

  // numberOfChanges: the total number of CVE IDs that have changed since the last update command/commit (new + updated)
  "numberOfChanges": 3,  

  // new: An array for CVEs that have been newly published since the last update command/commit (newly published, including any number of updates since it has been published until now)
  "new": [ 
    {
      // [new/updated].cveId: The CVE ID (that was newly published or updated)
      "cveId": "CVE-1970-0001",

      // [new/updated].cveOrgLink: Where you can find this record on the official CVE Project website. (The version here does not lag behind the live data).
      "cveOrgLink": "https://www.cve.org/CVERecord?id=CVE-1970-0001",

      // [new/updated].githubLink: Where you can find the raw JSON contents of this CVE (via this github repo).
      "githubLink": "https://raw.githubusercontent.com/CVEProject/cvelistV5/main/cves/1970/0xxx/CVE-1970-0001.json",

      // [new/updated].dateUpdated: The CVEID's cveMetadata.dateUpdated value (the last time it was updated before this update command/commit)
      "dateUpdated": "1969-12-31T23:59:59.999Z"
    }
  ],

  // updated: An array for CVEs that have been updated since the last update command/commit (CVE contents may have changed multiple times, but only the latest content is made available here). 
  // The items in the updated array follow the same pattern as the new array.
  "updated": [
    {
      "cveId": "CVE-1970-0002",
      "cveOrgLink": "https://www.cve.org/CVERecord?id=CVE-1970-0002",
      "githubLink": "https://raw.githubusercontent.com/CVEProject/cvelistV5/main/cves/1970/0xxx/CVE-1970-0002.json",
      "dateUpdated": "1969-12-31T23:59:59.999Z"
    },
    {
      "cveId": "CVE-1970-0003",
      "cveOrgLink": "https://www.cve.org/CVERecord?id=CVE-1970-0003",
      "githubLink": "https://raw.githubusercontent.com/CVEProject/cvelistV5/main/cves/1970/0xxx/CVE-1970-0003.json",
      "dateUpdated": "1969-12-31T23:59:59.999Z"
    }
  ],

  // error: This is meant to show CVE IDs that had an issue getting updated or for if something went wrong. 
  "error": []
}
```

The deltaLog file is just an array of the historical delta.json contents (including the latest delta.json contents).

Please note that the delta files are subject to change. If you wish to provide a new solution that the CVE team should implement, I suggest [joining the Automation Working Group (AWG)](https://www.cve.org/ProgramOrganization/WorkingGroups) which would be an appropriate place to suggest new features.

**Comment by M-nj** [comment]
These are valid concerns that can absolutely be brought up to the AWG group. 

For the time being, this repo is about as realtime as an unauthorized/anon user could get in a bulk format. I am honestly not sure if there will be a better option anytime in the near future. There is a cost concern with having many people hammer the CVE Services API with constant 'get changes since arbitrary timestamp' requests. 

These might not quash your concerns but here are some dev scripts that might be of interest to you:
## Check to see if remote git repo's latest commit matches your local version:
```sh
local=$(git log -n 1 --format=%H)
remote=$(git ls-remote https://github.com/CVEProject/cvelistv5.git main | awk '{print $1}')
if [ "$local" != "$remote" ]; then echo 'out of sync, needs git pull';else echo 'up to date'; fi
```

## Get CVE IDs changed since timestamp in repo (after a git pull)
```sh
timestamp="2025-03-03T05:00:00Z"
git pull
(git log --since=$timestamp --name-only --pretty=format: | sort -u | grep -oP "CVE-\d{4}-\d{4,}")
```
_NOTE: if a change was made at minute A, and the CVE Update command fetched at minute C, the change will show up in a query that starts at minute B_

**Comment by Sarrac3873** [comment]
> Hello,
> 
> First of all thank you for the awesome work you do concerning the CVE ecosystem!
> 
> I'm the developer of a CVE-related tool, and I would like to add the MITRE in my sources (instead of only relying on NVD for now). But to be honest I don't really know how to parse your feed.
> 
> So I would like to ask you the official and recommended way to synchronize our local databases with the new JSON 5.0 CVE list.
> 
> I searched on your blog posts and if I'm not wrong you're currently in "Soft Deploy" state, meaning CNAs now use the new format to declare CVEs. The "Hard Deploy" is targeted for 1st QT, 2023. At this moment we (as consumers) will be able to officially use the JSON 5.0 feeds.
> 
> But where to find the list please? I think the old format (`csv`, `html`, `text`, `xml`) will be removed, so maybe you will provide an API (or something similar as the [NVD does](https://nvd.nist.gov/developers/api-workflows)) to fetch the last changes?
> 
> Or maybe this current repo (cveproject/cvelistv5) will become our official data feeds?  If yes do you recommend to use the `recent_activities.json` file to detect the changes or simply periodically `git pull` and parse the new diffs?
> 
> Thank you in advance for your answer,
> Nicolas

**Comment by AnuarT79** [comment]
Ironing
