### ISSUE TITLE
Delta tarballs not generated at 0000Z, changes done in 2300-0000 missing

### ISSUE THREAD

**Issue by epozuelo** [CVEProject/cvelistV5#20]
Looking at the releases page, I see there's a full release at 0000Z, and then incremental releases with a delta tarball from the last full release every hour from 0100Z up to 2300Z. However, it seems to me that any changes from 2300Z until 0000Z will not be available in a delta tarball. That makes those delta tarballs a little less useful, as one will need to download a full tarball once a day anyway to stay up to date.

Could it be possible to have the 0000Z release contain a delta tarball from the previous 0000Z release? So that every change (including those done between 2300 and 0000) would be available in a delta tarball.

**Comment by hkong-mitre** [comment]
Nice catch!  And a good idea for a solution.  We are in the process of hosting the source code that generates the updates and releases into its own repository:  https://github.com/CVEProject/cvelist-bulk-download.  

Would you mind raising this issue there?  Keep this one here as well, since it does affect the releases in this repository.

Thanks.

**Comment by epozuelo** [comment]
Sure, opened as https://github.com/CVEProject/cvelist-bulk-download/issues/2

**Comment by hkong-mitre** [comment]
Thanks, @epozuelo.  I'll keep the issue open here as well as in https://github.com/CVEProject/cvelist-bulk-download/issues/2 until it is fixed since it is a bug that affects how the tarballs are used.

**Comment by hkong-mitre** [comment]
this is finally fixed and running with [this commit](https://github.com/CVEProject/cvelistV5/commit/8e1324e059e3863624dd718c7cd2756d2e7c4abe)
