### ISSUE TITLE
Retrive a list of published CVEs

### ISSUE THREAD

**Issue by jgamblin** [CVEProject/cvelistV5#47]
I need a continually updated list of all published CVE IDs.  Is this published anywhere as a list versus needing to pull all the CVE JSON records and parse them for the ID?

**Comment by hkong-mitre** [comment]
Interesting.  I just so happen to be writing a utility for doing this for another requirement, but it does need a git pull first from this repository since it walks the `cves` directory.  I'm curious if you need anything else besides the CVE ID, and what order the list should be sorted.  By default in the utility, the JSON array is sorted lexically, i.e., CVE-1970-11000 comes before CVE-1970-2000 (not real CVEs obviously) but provides an option to sort by `cveMetadata.dateUpdated`.

**Comment by jgamblin** [comment]
I just need the CVE ID for my project. I know there is a request for a CSV file of CVEs that I could use if that is in the pipeline and easier to produce. 

The sorted order doesn't matter for this project.

**Comment by hkong-mitre** [comment]
I've refactored this functionality out of the other feature branch, and it is currently in testing/review.  When that is complete, I will make a PR on https://github.com/CVEProject/cvelist-bulk-download.

**Comment by M-nj** [comment]
@Nabilabouelenin5 
Does the [cves/delta.json](https://github.com/CVEProject/cvelistV5/blob/main/cves/delta.json) and [cves/deltaLog.json](https://github.com/CVEProject/cvelistV5/blob/main/cves/deltaLog.json) contain the information you were looking for?
